site_name: FrostZ Wikipedia
site_description: Wiki page for Frostpunk-themed full conversion mod for DayZ
site_author: FrostZ Dev Team
site_url: https://frostzdev.github.io/Wiki/

copyright: "Copyright &copy; 2025 FrostZ Dev Team"

theme:
  palette:
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    - scheme: default
      #   primary: blue
      #   accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
  name: material
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.instant
    - search.highlight
  custom_dir: "docs/overrides"
  font:
    text: EB Garamond
    code: Regular
  logo: assets/images/logo.png

plugins:
  - search
  - mkdocstrings

extra_css:
  - assets/css/custom.css

markdown_extensions:
  - attr_list
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Buildings:
    - Buildings/Basics.md
    - Buildings/Upgrades.md
    - List of buildings:
        - Buildings/beacon.md
        - Buildings/cemetery.md
        - Buildings/Coal Mine.md
        - Buildings/cookhouse.md
        - Buildings/Execution Platform.md
        - Buildings/Fighting Pit.md
        - Buildings/Gathering Post.md
        - Buildings/generator.md
        - Buildings/hothouse.md
        - Buildings/Hunter's hut.md
        - Buildings/kiln.md
        - Buildings/Medical Post.md
        - Buildings/Public House.md
        - Buildings/Resource Depot.md
        - Buildings/sawmill.md
        - Buildings/steelworks.md
        - Buildings/Tentshack & Bunkhouse.md
        - Buildings/Wall Drill.md
        - Buildings/workshop.md
  - Crafting: Crafting/Crafting.md
  - Factions:
      - Factions/Lawkeepers.md
      - Factions/Faithkeepers.md
      - Factions/Frostlanders.md
      - Factions/Voting.md
  - Resources: Resources/Resources.md
  - Skills:
      - Skills/Basics.md
      - Skill trees:
          - Skills/Food & Health.md
          - Skills/Technology.md
          - Skills/Hunting & Exploration.md
  - PlayerStates:
      - PlayerStates/Heat Buffer.md
      - PlayerStates/Heat Level.md
      - PlayerStates/Frostbite.md
      - PlayerStates/Amputation.md
      - PlayerStates/Body Hygiene.md
      - PlayerStates/Food Diet.md
  - Heatstamps: Heatstamps.md
  

extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/8kC29NDt3c
